version: '3.3'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: viktoriiacherevan/lab4:django
    container_name: django
    networks: 
      - public
    ports: 
      - 80:8000
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.site
    image: viktoriiacherevan/lab4:monitor
    container_name: monitor
    networks: 
      - public

networks: 
  public:
    driver: bridge
